# Generated by Django 4.2.3 on 2023-07-11 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task1',
            new_name='Task',
        ),
    ]
